services:
  alpaca-bookmarks:
    build: .
    container_name: alpaca-bookmarks
    ports:
      # Map host port 8081 to container port 8081 (which Caddy listens on)
      - "${ALPACA_PORT:-8081}:8081"
    volumes:
      # Use a named volume to persist the SQLite database
      - alpaca_data:/data
      # - ./Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped
    environment:
      - TZ=${TZ:-America/Edmonton}
      # openssl rand -hex 32
      - JWT_SECRET=someSecret
    healthcheck:
      # This healthcheck pings the Go backend directly, which runs on port 8080 inside the container.
      # It mirrors the healthcheck defined in the Dockerfile.
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v1/ping"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"

volumes:
  alpaca_data:
